Dodano opcje przesłania jednego zadania razy kilka bez dzielenia na kilka osobnych
tqZK/harc_game_web pull request #101
Opened 2020-12-03 18:49 UTC by Antoni-Czaplicki

Jeśli harcerz zrobi np. 2 min deski (plank) to może wysłać jako jedno zadanie bez dzielenia filmików.

2020-12-03 22:03 UTC, tqZK requested changes
Dziękujemy za propozycję dodania ulepszenia do aplikacji 😃 
Twój kod nie uwzględnia tego, że niektóre zadania mają blokadę wykonywania (można wykonać je "raz dziennie" albo "raz w tygodniu"). Tylko zadania "bez ograniczeń" powinny mieć możliwość dodawania "ile razy wykonałem" zadanie (powinno być to uwzględnione w formularzu).
Poprawisz proszę? ☺️

2020-12-04 09:42 UTC, wdoganowski approved these changes

2020-12-04 09:45 UTC, wdoganowski commented on harc_game_web/apps/tasks/views.py
> +                if documented_task.how_many_times != 1:
Czy ta funkcja musi być tutaj?

2020-12-04 10:38 UTC, Antoni-Czaplicki commented on harc_game_web/apps/tasks/views.py
> +                if documented_task.how_many_times != 1:
Mogę ją przenieść

2023-04-14 10:45 UTC, closed without merging